name: pull Translations from Crowdin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-translations:
    runs-on: ubuntu-latest
    environment: crowdin

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: download, commit, and create PR
        uses: crowdin/github-action@v1.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          download_translations: true
          skip_untranslated_strings: false
          skip_untranslated_files: false
          export_only_approved: false
          create_pull_request: true
          
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}